apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: stackoverflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackoverflow
  template:
    metadata:
      labels:
        app: stackoverflow
    spec:
      containers:
        - name: stackoverflow
          image: raedwaili/stackoverflow:v1
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host